all: ex01_basicprogram ex02_parameters ex03_pid ex04_outerr ex05_in

ex01_basicprogram: ex01_basicprogram.c
	gcc -o $@ $<

ex02_parameters: ex02_parameters.c
	gcc -o $@ $<

ex03_pid: ex03_pid.c
	gcc -o $@ $<

ex04_outerr: ex04_outerr.c
	gcc -o $@ $<

ex05_in: ex05_in.c
	gcc -o $@ $<

clean:
	rm -f ex01_basicprogram ex02_parameters ex03_pid ex04_outerr ex05_in
